version: '3'

services:
  database:
    image: mysql:8.0.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports: 
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
